import type { Metadata } from 'next';
import Link from 'next/link';
import { Film, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';

export const metadata: Metadata = {
  title: 'About EditLocal — Free Private Media Tools',
  description: 'Learn how EditLocal provides free video and photo tools that process files locally without uploads, accounts, paid plans, or watermarked exports.',
  alternates: { canonical: '/about' },
};

export default function AboutPage() {
  return <main className="min-h-screen bg-background px-5 py-12 text-foreground"><article className="mx-auto max-w-3xl"><Link href="/" className="flex items-center gap-2.5 font-bold"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Film className="size-4" /></span>EditLocal</Link><h1 className="mt-12 text-4xl font-bold tracking-[-0.05em] sm:text-5xl">Media tools should be simple, private, and genuinely free.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">EditLocal is a browser-based toolkit for everyday video and photo work. It helps people reframe, compress, convert, trim, crop, merge, extract audio, create GIFs, and clean authorized overlays without transferring media to a remote processing service.</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{[[LockKeyhole,'Local by design','Media bytes stay in the current browser.'],[Sparkles,'Everything included','No plans, credits, trials, or export watermarks.'],[ShieldCheck,'Honest controls','Quality trade-offs and technical limits are explained.']].map(([Icon,title,text]) => { const FeatureIcon = Icon as typeof Film; return <section key={title as string} className="rounded-2xl border border-border bg-card p-5"><FeatureIcon className="size-5 text-violet-600" /><h2 className="mt-4 font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></section>; })}</div><h2 className="mt-12 text-2xl font-bold">How local processing works</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">EditLocal loads a bundled FFmpeg WebAssembly engine into a browser worker. Selected files are placed in temporary browser memory, processed on the device, and returned as downloadable object URLs. The original file is never overwritten. Temporary data disappears when the session is cleared or closed.</p><h2 className="mt-10 text-2xl font-bold">A sustainable free product</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">All product features and quality modes are available to everyone. Vercel Web Analytics may measure page visits after deployment so the site owner can understand which tools are useful. Analytics does not receive selected video, photo, or audio files.</p></article></main>;
}
